import { User, Task } from "@/types";
import { hashPassword } from "./crypto";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Vylex",
    email: "vylex@email.com",
    passwordHash: hashPassword("123456"),
    createdAt: new Date("2024-01-01"),
    isActive: true,
  },
  {
    id: "2",
    name: "Usuário Teste",
    email: "teste@email.com",
    passwordHash: hashPassword("123456"),
    createdAt: new Date("2024-01-02"),
    isActive: true,
  },
];

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Implementar autenticação",
    description: "Criar sistema de login e registro de usuários",
    status: "completed",
    dueDate: new Date("2024-01-15"),
    userId: "1",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-15"),
    priority: "high",
    tags: ["autenticação", "segurança"],
  },
  {
    id: "2",
    title: "Criar dashboard",
    description: "Desenvolver interface principal do sistema",
    status: "in_progress",
    dueDate: new Date("2024-01-20"),
    userId: "1",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-16"),
    priority: "medium",
    tags: ["ui", "dashboard"],
  },
  {
    id: "3",
    title: "Implementar CRUD de tarefas",
    description: "Criar operações de criar, ler, atualizar e deletar tarefas",
    status: "pending",
    dueDate: new Date("2024-01-25"),
    userId: "1",
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-14"),
    priority: "high",
    tags: ["crud", "tarefas"],
  },
  {
    id: "4",
    title: "Configurar testes",
    description: "Implementar testes unitários e de integração",
    status: "pending",
    dueDate: new Date("2024-01-30"),
    userId: "2",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    priority: "medium",
    tags: ["testes", "qualidade"],
  },
  {
    id: "5",
    title: "Documentar API",
    description: "Criar documentação completa da API",
    status: "in_progress",
    dueDate: new Date("2024-02-01"),
    userId: "2",
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-17"),
    priority: "low",
    tags: ["documentação", "api"],
  },
  {
    id: "6",
    title: "Otimizar performance",
    description: "Melhorar performance da aplicação",
    status: "pending",
    dueDate: new Date("2024-02-05"),
    userId: "1",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
    priority: "urgent",
    tags: ["performance", "otimização"],
  },
];
